<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 09.11.2018
 * Time: 15:25
 */

namespace wscvua\faq;

use Yii;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'wscvua\faq\controllers';

    public $languages = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!sizeof(!$this->languages)){
            $this->languages[] = Yii::$app->language;
        }
    }
}